name: IoT Edge Device CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build firmware
        run: make -C chapter-10 firmware

      - name: Run tests
        run: make -C chapter-10 test

      # - name: Deploy to Edge Device
      #   # Here you can connect to the server and reboot the firmware
      #   run: ssh user@edge_device 'sudo reboot'
