name: IoT Edge Device CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build firmware
        run: make firmware
      - name: Run tests
        run: make test
      - name: Deploy to Edge Device (disabled)
        if: ${{ false }}
        run: echo "deploy disabled for now"

